//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morse {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MorseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MorseResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Morse.MorseResources", typeof(MorseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   @azamshul に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authorize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string authorize {
            get {
                return ResourceManager.GetString("authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://azam.io に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string authorUrl {
            get {
                return ResourceManager.GetString("authorUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Morse by @azamshul に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Twitter plugin for KanColleViewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pluginDescription {
            get {
                return ResourceManager.GetString("pluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Morse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pluginName {
            get {
                return ResourceManager.GetString("pluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter status here and press &quot;Send&quot; or Ctrl-Enter to send に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string statusPlaceholder {
            get {
                return ResourceManager.GetString("statusPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter hashtags, etc. to be prepended to all statuses に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tagsPlaceholder {
            get {
                return ResourceManager.GetString("tagsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter verification code here and press &quot;Verify&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string verifierPlaceholder {
            get {
                return ResourceManager.GetString("verifierPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string verify {
            get {
                return ResourceManager.GetString("verify", resourceCulture);
            }
        }
    }
}
